---
# tasks file for deploy_docker_on_app
- block: 
  - name: Install apt-transport-https
    apt:
      name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
      state: latest
      update_cache: yes

  - name: Add signing key
    apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

  - name: Add repository into sources list
    apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

  - name: Install Docker 
    apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: yes

  - name: Start Docker
    ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started

  when: ansible_os_family == "Debian" 

- block: 

    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
    
    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started

  when: ansible_os_family == "RedHat" 





