---
# tasks file for deploy_postgresql_server

- name: Add repository into sources list
  apt_repository:
        repo: "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt {{ansible_lsb.codename}}-pgdg main"
        state: present
        filename: postgresql

- name: Add signing key
  apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

- name: install postresql "{{postresql_version}}"
  apt:
    name:
          - postgresql-{{postresql_version}}
    update_cache: true
    state: latest
    
- name: Copy modify template postgresql.conf
  template:
    src: postgresql.j2
    dest: "{{postgresql_conf}}"
  notify: Restart Postgresql  

